version: "3"

services:
    api:
      image: mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-5.0
      environment:
       ASPNETCORE_ENVIRONMENT: Development
       ConnectionStrings_default: mongodb://root:developmenT!@mongo:27017/
      depends_on:
        - mongo
    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: developmenT!
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_URL: mongodb://root:developmenT!@mongo:27017/
      depends_on:
        - mongo